//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.RescueEquipmentSet = new HashSet<RescueEquipmentSet>();
            this.EmergencyTeamDeparture = new HashSet<EmergencyTeamDeparture>();
        }
    
        public int CarId { get; set; }
        public string CarNumber { get; set; }
        public string CarBrand { get; set; }
        public string CarModel { get; set; }
        public string CarCondition { get; set; }
    
        public virtual ICollection<RescueEquipmentSet> RescueEquipmentSet { get; set; }
        public virtual ICollection<EmergencyTeamDeparture> EmergencyTeamDeparture { get; set; }
    }
}
