//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyTeamDeparture
    {
        public int DepartureId { get; set; }
        public int RequestId { get; set; }
        public int EmergencyTeamId { get; set; }
        public int CarId { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual EmergencyTeam EmergencyTeam { get; set; }
        public virtual Request Request { get; set; }
    }
}
