//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyTeam
    {
        public EmergencyTeam()
        {
            this.Driver = new HashSet<Driver>();
            this.Rescuer = new HashSet<Rescuer>();
            this.EmergencyTeamDeparture = new HashSet<EmergencyTeamDeparture>();
        }
    
        public int EmergencyTeamId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string EmergencyTeamName { get; set; }
    
        public virtual ICollection<Driver> Driver { get; set; }
        public virtual ICollection<Rescuer> Rescuer { get; set; }
        public virtual ICollection<EmergencyTeamDeparture> EmergencyTeamDeparture { get; set; }
    }
}
