//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int UserId { get; set; }
        public int JobTitleId { get; set; }
        public Nullable<int> PersonalNumber { get; set; }
        public string WorkPhone { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual UserInformation UserInformation { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual Rescuer Rescuer { get; set; }
    }
}
