//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatus
    {
        public RequestStatus()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int RequestStatusId { get; set; }
        public string RequestStatusName { get; set; }
    
        public virtual ICollection<Request> Request { get; set; }
    }
}
