//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rescuer
    {
        public int UserId { get; set; }
        public int EmergencyTeamId { get; set; }
        public Nullable<bool> HeadOfGroup { get; set; }
        public Nullable<System.DateTime> MedicalBoardPassageDate { get; set; }
    
        public virtual EmergencyTeam EmergencyTeam { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
